//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCRM.Web.Models
{
    using System;using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        [Key]public long OrderID { get; set; }
        [Key]public long OrderLine { get; set; }
        public string Discount { get; set; }
        public string ProductID { get; set; }
        public long Quantity { get; set; }
        public long TaxType { get; set; }
        public string UnitPrice { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
