'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class Categories
    <Key> Public Property CategoryID As Long
     Public Property Description As String
     Public Property Name As String
     Public Property Picture As Byte()
     Public Property Thumbnail As Byte()

End Class
