//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCRM.Web.Models
{
    using System;using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        [Key]public long CustomerID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string BirthDate { get; set; }
        public Nullable<long> ChildrenAtHome { get; set; }
        public string City { get; set; }
        public string CountryCode { get; set; }
        public string CreatedOn { get; set; }
        public string Education { get; set; }
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string Gender { get; set; }
        public Nullable<long> IsHouseOwner { get; set; }
        public string LastModifiedOn { get; set; }
        public string LastName { get; set; }
        public string MaritalStatus { get; set; }
        public string MiddleName { get; set; }
        public Nullable<long> NumberCarsOwned { get; set; }
        public string Occupation { get; set; }
        public string Phone { get; set; }
        public byte[] Picture { get; set; }
        public string PostalCode { get; set; }
        public string Region { get; set; }
        public string SearchTerms { get; set; }
        public string Suffix { get; set; }
        public byte[] Thumbnail { get; set; }
        public string Title { get; set; }
        public Nullable<long> TotalChildren { get; set; }
        public string YearlyIncome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
