'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class Customers
    <Key> Public Property CustomerID As Long
     Public Property AddressLine1 As String
     Public Property AddressLine2 As String
     Public Property BirthDate As String
     Public Property ChildrenAtHome As Nullable(Of Long)
     Public Property City As String
     Public Property CountryCode As String
     Public Property CreatedOn As String
     Public Property Education As String
     Public Property EmailAddress As String
     Public Property FirstName As String
     Public Property Gender As String
     Public Property IsHouseOwner As Nullable(Of Long)
     Public Property LastModifiedOn As String
     Public Property LastName As String
     Public Property MaritalStatus As String
     Public Property MiddleName As String
     Public Property NumberCarsOwned As Nullable(Of Long)
     Public Property Occupation As String
     Public Property Phone As String
     Public Property Picture As Byte()
     Public Property PostalCode As String
     Public Property Region As String
     Public Property SearchTerms As String
     Public Property Suffix As String
     Public Property Thumbnail As Byte()
     Public Property Title As String
     Public Property TotalChildren As Nullable(Of Long)
     Public Property YearlyIncome As String

     Public Overridable Property Orders As ICollection(Of Orders) = New HashSet(Of Orders)

End Class
