//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCRM.Web.Models
{
    using System;using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        [Key]public long OrderID { get; set; }
        public long CustomerID { get; set; }
        public Nullable<long> DeliveredDateUTC { get; set; }
        public long LastModifiedOnUTC { get; set; }
        public long OrderDateUTC { get; set; }
        public Nullable<long> PaymentType { get; set; }
        public string SearchTerms { get; set; }
        public string ShipAddress { get; set; }
        public string ShipCity { get; set; }
        public string ShipCountryCode { get; set; }
        public string ShipPhone { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipRegion { get; set; }
        public Nullable<long> ShipVia { get; set; }
        public Nullable<long> ShippedDateUTC { get; set; }
        public long Status { get; set; }
        public string TrackingNumber { get; set; }
    
        public virtual CountryCode CountryCode { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual PaymentType PaymentType1 { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
    }
}
