'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class OrderItems
    <Key> Public Property OrderID As Long
    <Key> Public Property OrderLine As Long
     Public Property Discount As String
     Public Property ProductID As String
     Public Property Quantity As Long
     Public Property TaxType As Long
     Public Property UnitPrice As String

     Public Overridable Property Products As Products
     Public Overridable Property Orders As Orders

End Class
