'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class Orders
    <Key> Public Property OrderID As Long
     Public Property CustomerID As Long
     Public Property DeliveredDate As String
     Public Property LastModifiedOn As String
     Public Property OrderDate As String
     Public Property PaymentType As Nullable(Of Long)
     Public Property SearchTerms As String
     Public Property ShipAddress As String
     Public Property ShipCity As String
     Public Property ShipCountryCode As String
     Public Property ShipPhone As String
     Public Property ShipPostalCode As String
     Public Property ShipRegion As String
     Public Property ShipVia As Nullable(Of Long)
     Public Property ShippedDate As String
     Public Property Status As Long
     Public Property TrackingNumber As String

     Public Overridable Property Customers As Customers
     Public Overridable Property OrderItems As ICollection(Of OrderItems) = New HashSet(Of OrderItems)

End Class
