//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCRM.Web.Models
{
    using System;using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        [Key]public string ProductID { get; set; }
        public long CategoryID { get; set; }
        public string Color { get; set; }
        public string CreatedOn { get; set; }
        public string DealerPrice { get; set; }
        public string Description { get; set; }
        public string Discount { get; set; }
        public string DiscountEndDate { get; set; }
        public string DiscountStartDate { get; set; }
        public string LastModifiedOn { get; set; }
        public string ListPrice { get; set; }
        public string Name { get; set; }
        public byte[] Picture { get; set; }
        public long SafetyStockLevel { get; set; }
        public string SearchTerms { get; set; }
        public string Size { get; set; }
        public long StockUnits { get; set; }
        public long TaxType { get; set; }
        public byte[] Thumbnail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}
