'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class Products
    <Key> Public Property ProductID As String
     Public Property CategoryID As Long
     Public Property Color As String
     Public Property CreatedOn As String
     Public Property DealerPrice As String
     Public Property Description As String
     Public Property Discount As String
     Public Property DiscountEndDate As String
     Public Property DiscountStartDate As String
     Public Property LastModifiedOn As String
     Public Property ListPrice As String
     Public Property Name As String
     Public Property Picture As Byte()
     Public Property SafetyStockLevel As Long
     Public Property SearchTerms As String
     Public Property Size As String
     Public Property StockUnits As Long
     Public Property TaxType As Long
     Public Property Thumbnail As Byte()

     Public Overridable Property OrderItems As ICollection(Of OrderItems) = New HashSet(Of OrderItems)

End Class
