'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SampleCRMEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SampleCRMEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categories() As DbSet(Of Categories)
    Public Overridable Property CountryCodes() As DbSet(Of CountryCodes)
    Public Overridable Property Customers() As DbSet(Of Customers)
    Public Overridable Property DbVersion() As DbSet(Of DbVersion)
    Public Overridable Property OrderItems() As DbSet(Of OrderItems)
    Public Overridable Property Orders() As DbSet(Of Orders)
    Public Overridable Property OrderStatus() As DbSet(Of OrderStatus)
    Public Overridable Property PaymentTypes() As DbSet(Of PaymentTypes)
    Public Overridable Property Products() As DbSet(Of Products)
    Public Overridable Property Shippers() As DbSet(Of Shippers)
    Public Overridable Property TaxTypes() As DbSet(Of TaxTypes)

End Class
